filebeat.inputs:
- type: log
  enabled: true

  paths:
  - /opt/cortex/output.json
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true
  json.expand_keys: false
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml


  reload.enabled: false
output.logstash:
  hosts: ["10.1.1.85:5044"]
